-- SalonNow initial schema
-- Standalone project: do not connect this schema to Karaji/Sayyarti.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  role text not null default 'customer' check (role in ('customer','salon_owner','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.salons (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) on delete set null,
  name text not null,
  gender text not null check (gender in ('men','women')),
  description text,
  phone text,
  address text,
  latitude double precision,
  longitude double precision,
  google_maps_url text,
  google_place_id text,
  google_rating numeric(2,1),
  opening_hours jsonb not null default '{}'::jsonb,
  is_open boolean not null default false,
  is_verified boolean not null default false,
  wait_status text not null default 'unknown' check (wait_status in ('available','moderate','busy','unknown')),
  estimated_wait_minutes integer check (estimated_wait_minutes is null or estimated_wait_minutes >= 0),
  last_queue_update_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  salon_id bigint not null references public.salons(id) on delete cascade,
  name text not null,
  price numeric(10,2) not null check (price >= 0),
  duration_minutes integer not null check (duration_minutes > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.salon_staff (
  id bigint generated by default as identity primary key,
  salon_id bigint not null references public.salons(id) on delete cascade,
  name text not null,
  role_title text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.queue_entries (
  id bigint generated by default as identity primary key,
  salon_id bigint not null references public.salons(id) on delete cascade,
  customer_id uuid references public.profiles(id) on delete set null,
  service_id bigint references public.services(id) on delete set null,
  source text not null default 'walk_in' check (source in ('walk_in','app')),
  status text not null default 'waiting' check (status in ('waiting','in_service','completed','cancelled','no_show')),
  position integer,
  estimated_wait_minutes integer check (estimated_wait_minutes is null or estimated_wait_minutes >= 0),
  joined_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  notes text
);

create index if not exists salons_gender_idx on public.salons(gender);
create index if not exists salons_owner_id_idx on public.salons(owner_id);
create index if not exists services_salon_id_idx on public.services(salon_id);
create index if not exists salon_staff_salon_id_idx on public.salon_staff(salon_id);
create index if not exists queue_entries_salon_status_idx on public.queue_entries(salon_id,status);
create index if not exists queue_entries_customer_id_idx on public.queue_entries(customer_id);

alter table public.profiles enable row level security;
alter table public.salons enable row level security;
alter table public.services enable row level security;
alter table public.salon_staff enable row level security;
alter table public.queue_entries enable row level security;

grant select on public.salons to anon;
grant select on public.services to anon;
grant select on public.salon_staff to anon;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.salons to authenticated;
grant select, insert, update, delete on public.services to authenticated;
grant select, insert, update, delete on public.salon_staff to authenticated;
grant select, insert, update, delete on public.queue_entries to authenticated;

create policy "Public can view verified salons"
on public.salons for select
to anon, authenticated
using (is_verified = true);

create policy "Owners can manage their salon"
on public.salons for all
to authenticated
using (owner_id = (select auth.uid()))
with check (owner_id = (select auth.uid()));

create policy "Public can view active services of verified salons"
on public.services for select
to anon, authenticated
using (is_active = true and exists (select 1 from public.salons s where s.id = salon_id and s.is_verified = true));

create policy "Owners can manage services for their salon"
on public.services for all
to authenticated
using (exists (select 1 from public.salons s where s.id = salon_id and s.owner_id = (select auth.uid())))
with check (exists (select 1 from public.salons s where s.id = salon_id and s.owner_id = (select auth.uid())));

create policy "Owners can manage staff for their salon"
on public.salon_staff for all
to authenticated
using (exists (select 1 from public.salons s where s.id = salon_id and s.owner_id = (select auth.uid())))
with check (exists (select 1 from public.salons s where s.id = salon_id and s.owner_id = (select auth.uid())));

create policy "Customers can view queue status for verified salons"
on public.queue_entries for select
to anon, authenticated
using (exists (select 1 from public.salons s where s.id = salon_id and s.is_verified = true));

create policy "Owners can manage queue for their salon"
on public.queue_entries for all
to authenticated
using (exists (select 1 from public.salons s where s.id = salon_id and s.owner_id = (select auth.uid())))
with check (exists (select 1 from public.salons s where s.id = salon_id and s.owner_id = (select auth.uid())));

create policy "Customers can manage their own profile"
on public.profiles for all
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

-- Keep updated_at current without extensions.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();

drop trigger if exists salons_set_updated_at on public.salons;
create trigger salons_set_updated_at before update on public.salons for each row execute function public.set_updated_at();

drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at before update on public.services for each row execute function public.set_updated_at();
